
###
GET http://localhost:3000/subscribers
###
GET http://localhost:3000/subscribers
654335539d301972cf1b844d

###
POST http://localhost:3000/subscribers

###
DELETE http://localhost:3000/subscribers


###
PATCH http://localhost:3000/subscribers
